### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by stolnt** [maartenvanderaart/keymaker#2]
When running this command:
# curl http://localhost:4567/updatepassword/foo/$(hostname -a)

You get this:
<html><body><h2>404 Not found</h2></body></html>

From the man page of hostname:
       -a, --alias
              Display the alias name of the host (if  used).  This  option  is
              deprecated and should not be used anymore.

**Comment by maartenvanderaart** [comment]
This was an error in the example, -a ought to have been -f. Of course, just $(hostname) would work as well and in a smallish environment with just a single domain this would suffice. The example was fixed in 36344862f811f0aa0b3cb14a37ab4ef61809f2fd.
