### ISSUE TITLE
Please FIX: configurable password length

### ISSUE THREAD

**Issue by stolnt** [maartenvanderaart/keymaker#3]
Please make the password length configurable. I am disappointed that this is fixed length!!

**Comment by maartenvanderaart** [comment]
Password now accepts a length parameter, though in Main it is statically called with a length of 60. Might not be enough to solve your disappointment, but should suffice for security purposes.

**Comment by maartenvanderaart** [comment]
Fixed in 770ca12ba73abe14b7170ddce458945bd9146351, specify password length in `keymaker.properties`.
